# Generated by Django 5.2.1 on 2025-07-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.AutoField(db_column='Topic_id', primary_key=True, serialize=False)),
                ('Topic', models.TextField(blank=True, db_column='Topic', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('configuration_img', models.ImageField(blank=True, db_column='Image', null=True, upload_to='uploads/topics/')),
            ],
            options={
                'db_table': 'Topics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(db_column='Question_id', primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, db_column='Question', null=True)),
                ('option1', models.TextField(blank=True, db_column='Option1', null=True)),
                ('option2', models.TextField(blank=True, db_column='Option2', null=True)),
                ('option3', models.TextField(blank=True, db_column='Option3', null=True)),
                ('option4', models.TextField(blank=True, db_column='Option4', null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('topic_id', models.ForeignKey(blank=True, db_column='Topic_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_app.topics')),
            ],
            options={
                'db_table': 'Questions',
                'managed': True,
            },
        ),
    ]
