# Generated by Django 5.2.1 on 2025-07-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='Topic',
        ),
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.TextField(blank=True, db_column='option1', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.TextField(blank=True, db_column='option2', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.TextField(blank=True, db_column='option3', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.TextField(blank=True, db_column='option4', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True, db_column='question', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_id',
            field=models.AutoField(db_column='question_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='topic_id',
            field=models.ForeignKey(blank=True, db_column='topic_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_app.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='configuration_img',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='uploads/topics/'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_id',
            field=models.AutoField(db_column='topic_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='topics',
            name='topic',
            field=models.TextField(blank=True, db_column='topic', null=True),
        ),
    ]
