# Generated by Django 5.2.1 on 2025-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_topics_topic_alter_questions_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='des_img',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='uploads/topics/'),
        ),
    ]
