# Generated by Django 5.2.1 on 2025-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_questions_des_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='des_img',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='uploads/questions/'),
        ),
    ]
