# Generated by Django 5.2.1 on 2025-07-23 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_questions_des_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic',
            field=models.TextField(blank=True, db_column='topic', max_length=100, null=True),
        ),
    ]
