# Generated by Django 5.2.1 on 2025-07-23 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_topics_created_at_topics_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
