# Generated by Django 5.2.1 on 2025-07-28 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_topics_created_at_alter_quizresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='topic',
            field=models.TextField(blank=True, db_column='topic', max_length=100, null=True),
        ),
    ]
